### ISSUE TITLE
单曲循环 随机 播放模式有问题

### ISSUE THREAD

**Issue by HApple** [wh8817221/YYMusic#1]
列表中选中一首歌 -> PlayerManager -> playMusic -> playReplaceItem -> 赋值给 self.playModel 
autoPlay()  里 取的又是 currentModel
autoPlay未完善循环和随机逻辑

**Comment by wh8817221** [comment]
这个只是我闲着自己写的demo,你可以自己根据需求修改

**Comment by HApple** [comment]
closed
